
#Basics of Python



Text

# Everything in blocks of spaces
No more {},[],()

In [ ]:
a=10
print(a)

10


# MultiLine statements 

In [ ]:
mark1=40
mark2=50
mark3=60
total=mark1+\
mark2+\
mark3
avg=total/3
print (avg)

50.0


In [ ]:
Num=['1','2','3',
    '4','5','6']
print (Num)

['1', '2', '3', '4', '5', '6']


# Quotes and Comments

In [ ]:
word = 'word'
sentence = "This is a sentence."
paragraph = """This is a paragraph. It is
made up of multiple lines and sentences."""
print (word)
print (sentence)
print (paragraph)


word
This is a sentence.
This is a paragraph. It is
made up of multiple lines and sentences.


In [ ]:
#in line comment
#This is a comment similiar to // in c.
"""this is blockwise comment similiar to /* c style */ but it doesn't ecohs"""
'''this is blockwise comment similiar to /* c style */ but it ecohs'''


'this is blockwise comment similiar to /* c style */ but it ecohs'

# Example 1:

Write a program that takes three numbers and prints their sum. Every number is given on a separate line. 

In [ ]:
a = int(input())
b = int(input())
c = int(input())

print(a + b + c)

10
20
30
60


# Example 2:
Given the integer N - the number of minutes that is passed since midnight - how many hours and minutes are displayed on the 24h digital clock?
The program should print two numbers: the number of hours (between 0 and 23) and the number of minutes (between 0 and 59).

For example, if N = 150, then 150 minutes have passed since midnight - i.e. now is 2:30 am. So the program should print 2 30.



In [ ]:
N=eval(input("enter n"))
H=N//60
M=N%60 
H=H%24
print ("time is=",H,":",M)

enter n180
time is= 3 : 0


# Example 3:
N students take K apples (where K>N) and distribute them among each other evenly. The remaining (the undivisible) part remains in the basket. How many apples will each single student get? How many apples will remain in the basket?

In [ ]:
N=int(input("enter no of students"))
K=int(input("enter no of apples"))
D=K//N
R=K%N
print("total no of students={},\
each student got {} no of apples, \
still {} no of apples remain on the basket".format(N,D,R))

enter no of students120
enter no of apples160
total no of students=120,each student got 1 no of apples, still 40 no of apples remain on the basket


# **Example 4:** Finding roots of a quadratic equation

In [ ]:
import math
a=eval(input('a'))
b=eval(input('b'))
c=eval(input('c'))
d=(((b**2)-4*a*c))
print (d)
e=math.sqrt(abs(d))
x1=(-b+e)/(2*a)
x2=(-b-e)/(2*a)
print("roots of the equation are {} , {}".format(x1,x2))


a20
b30
c60
-3900
roots of the equation are 0.8112494995995995 , -2.3112494995995996


# Example 5:
Write a program that greets the user by printing the word "Hello", a comma, the name of the user and an exclamation mark after it. See the examples below.
ex:
    input='Mr. President'
    
    
    Hello, Mr. President!

In [ ]:
n=input()
k=n+'!'
print ('Hello,',k)

President
Hello, President!


### **Control statements**

# Example 6:
Given the two integers, print the least of them.

In [ ]:
a=int(input())
b=int(input())
if a<b:
    print (a)
else:
    print (b)

20
30
20


## **Loops**

# Examplle 7:
Write a program to compute 1/2+2/3+3/4+...+n/n+1 with a given n input by console (n>0).


In [ ]:
n=int(input())
res=0
for i in range(1,n+1):
    res+=float(float(i)/i+1)
print (res)

20
40.0


### **Basics of NumPy**

# **Importing Numpy Package: refer to numpy documentation (https://numpy.org/doc/stable/) for more information.**


In [ ]:
import numpy as np

Creating 1D array


In [ ]:
oneDimensionalData=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Printing the size or shape of the array

In [ ]:
print(oneDimensionalData.shape)

(9,)


In [ ]:
one_R=oneDimensionalData.reshape([1,9])
one_R.shape
one_R

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

Accessing the elements of 1D array

*   index start with 0
*   syntax arrray_name[index]




In [ ]:
print (oneDimensionalData[0])

1


Creating 2D array


In [ ]:
twoDimensionalArray = np.array([[1,2,3],[4,5,6],[7,8,9]])


Printing the size or shape of the array

In [ ]:
twoDimensionalArray.shape

(3, 3)

Printing contents of 2D array

In [ ]:
print(twoDimensionalArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Accessing the elements of 2D array

*   index start with 0
*   syntax arrray_name[index_row,index_column]




In [ ]:
print(twoDimensionalArray[2,1])

8


In [ ]:
print(twoDimensionalArray[1,0])

4


Accessing the contents of the numpy array using slicing and striding

In [ ]:
oneDimensionalData

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
print(oneDimensionalData[1:4])

[2 3 4]


In [ ]:
print(oneDimensionalData[0:9:2])

[1 3 5 7 9]


In [ ]:
print(twoDimensionalArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(twoDimensionalArray[::2,::2])

[[1 3]
 [7 9]]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Concatenating Arrays Together
arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Creating an Numpy array with floating point data

In [ ]:
Nf_array1=np.array([3.12,4.45,234.543,.23,523.234,2.2],'float16')

In [ ]:
print(Nf_array1)

[3.119e+00 4.449e+00 2.345e+02 2.300e-01 5.230e+02 2.199e+00]


In [ ]:
print(Nf_array1.dtype)

float16


In [ ]:
Nf_array2=np.array([2.324,432.243,12312.2,.33,5.4],'float32')

In [ ]:
print(Nf_array2)

[2.32400e+00 4.32243e+02 1.23122e+04 3.30000e-01 5.40000e+00]


In [ ]:
print(Nf_array2.dtype)

float32


np.zeros(shape) will create an array filled with 0 values with the specified shape. The default dtype is float64.

In [ ]:
np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

ones(shape) will create an array filled with 1 values. It is identical to zeros in all other respects.

In [ ]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

np.arange() will create arrays with regularly incrementing values. Refer documentation for using arrange on various cases

In [ ]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

np.linspace() will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values. [syntax np.linspace(begin_value,end_value,no_ele)]

In [ ]:
np.linspace(2,3,10)

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [ ]:
np.linspace(3,6,6)

array([3. , 3.6, 4.2, 4.8, 5.4, 6. ])

In [ ]:
#skip this line
#below command creates the numpy array with 20 elements
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])